src/wroblewshop/views/auth.py
from functools import wraps
from typing import Callable, ParamSpec, TypeVar

import inject
from authlib.integrations.flask_client import OAuth
from authlib.oidc.core import UserInfo
from flask import (
    Blueprint,
    Response,
    current_app,
    redirect,
    render_template,
    session,
    url_for,
)
from werkzeug import Response as BaseResponse

from wroblewshop.domain.user import UserRepository

bp = Blueprint("auth", __name__)


@bp.get("")
@inject.autoparams()
def callback(users: UserRepository) -> BaseResponse:
    oauth = _get_oauth()
    # TODO: flask test for checking iss and aud
    server_metadata = oauth.google.load_server_metadata()
    token = oauth.google.authorize_access_token(
        claims_options={
            "iss": {"value": server_metadata.get("issuer")},
            "aud": {"value": oauth.google.client_id},
        }
    )
    user = oauth.google.userinfo(token=token)

    if not _is_authorised(user, users):
        return redirect(url_for("auth.forbidden"))

    session["user"] = user

    return redirect(url_for("home.index"))


def _is_authorised(user: UserInfo, users: UserRepository) -> bool:
    return users.get_by_email(user["email"]) is not None


@bp.get("/forbidden")
def forbidden() -> Response:
    return Response(render_template("forbidden.html"), status=403)


@bp.get("/logout")
def logout() -> BaseResponse:
    session.pop("user", None)
    return redirect(url_for("start.index"))


T = TypeVar("T")
P = ParamSpec("P")


def secure(func: Callable[P, T]) -> Callable[P, T | Response]:
    @wraps(func)
    def decorated_function(*args: P.args, **kwargs: P.kwargs) -> T | Response:
        if "user" not in session:
            oauth = _get_oauth()
            callback_url = url_for("auth.callback", _external=True)
            response: Response = oauth.google.authorize_redirect(callback_url)
            return response
        return func(*args, **kwargs)

    return decorated_function


def _get_oauth() -> OAuth:
    return current_app.extensions["authlib.integrations.flask_client"]

src/wroblewshop/views/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='app.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
    <title>Wroblewshop</title>
</head>
<body>
{% block header %}
<header class="navbar bg-body-tertiary shadow-sm">
    <div class="container">
        {% block header_title %}<a class="navbar-brand app-brand" href="{{ url_for('start.index') }}">Wroblewshop</a>{% endblock %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Sign Out</a>
            </li>
        </ul>
    </div>
</header>
{% endblock %}
<main class="container-fluid">
    <div class="row g-0 mb-4">
        {% block beforeContent %}{% endblock %}
    </div>
    <div class="row g-0">
        <div class="col-lg-3"></div>
        {% block main %}{% endblock %}
        <div class="col-lg-3"></div>
    </div>
</main>
</body>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</html>

src/wroblewshop/views/templates/_page-two-third-width.html
{% extends '_base.html' %}

{% block main %}
<section class="col-lg-6 pt-3">
    <div class="column-two-thirds">
        {% block content %}{% endblock %}
    </div>
</section>
{% endblock %}

src/wroblewshop/views/templates/add-item.html
{% extends '_page-two-third-width.html' %}

{% block content %}
<h2>Add item</h2>

<form method="post" action="/item" aria-label="add-item" novalidate>
    {{ form.csrf_token }}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div id="invalid-csrf" class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <fieldset class="form-group mb-3">
        {{ form.name.label(class_="form-label") }}
        {% if form.name.errors %}
            {{ form.name(class_="form-control is-invalid", aria_describedby="invalidNameFeedback") }}
            {% for error in form.name.errors %}
            <div id="invalidNameFeedback" class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        {% else %}
            {{ form.name(class_="form-control") }}
        {% endif %}
    </fieldset>
    <input class="btn btn-success" type="submit" value="Confirm" role="button">
</form>
<hr/>
<section>
    <h3>Cupboard Items</h3>
    {% for item in items %}
    <form method="post" action="{{ url_for('item.delete_item', item_id=item.id) }}" aria-label="delete-item" novalidate>
        {{ item.form.csrf_token }}
        {% for field in item.form if field.name != "csrf_token" %}
        <div class="row" role="row">
            <div class="col">
                {{ field.label() }}
            </div>
            <div class="col" role="row">
                {{ field(value="Delete") }}
            </div>
        </div>
        {% endfor %}
    </form>
    {% endfor %}
</section>
{% endblock %}

src/wroblewshop/views/templates/forbidden.html
{% extends '_page-two-third-width.html' %}

{% block content %}
<h2>Forbidden</h2>
<p>These aren't the droids your looking for...</p>
{% endblock %}

src/wroblewshop/views/templates/home.html
{% extends '_page-two-third-width.html' %}

{% block content %}
<h2>{{ cupboard_name }} Cupboard</h2>
<p>Select an action to start:</p>
<section class="actions-list">
    <ul>
        <li>
            <a href="{{ url_for('item.index') }}">Add item</a>
        </li>
    </ul>

</section>
{% endblock %}

src/wroblewshop/views/templates/start.html
{% extends '_page-two-third-width.html' %}

{% block header %}
    <header class="navbar bg-body-tertiary shadow-sm">
        <div class="container">
            {% block header_title %}<a class="navbar-brand app-brand" href="{{ url_for('start.index') }}">Wroblewshop</a>{% endblock %}
        </div>
    </header>
{% endblock %}

{% block content %}
<h2>Welcome to Wroblewshop</h2>
<a class="btn btn-primary" href="{{ url_for('home.index') }}" role="button">Start</a>
{% endblock %}